language: cpp
compiler: g++

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -y gdb

before_script:
- ulimit -c unlimited -S # enable core files

script: "bash -c ./build.sh"

after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

