language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"
- sudo apt-get install -y gdb

before_script:
- ulimit -c unlimited -S # enable core files
- cat /proc/sys/kernel/core_pattern # show core pattern

script: "bash -c ./build.sh"

after_failure:
- echo "checking for core file"
- ls -al .
- if [[ -f core ]]; then echo "found a core file"; gdb -c core bin/arangod -ex "thread apply all bt full" -ex "set pagination 0" -batch; fi

